name: Deploy to CloudPanel Server

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 65.109.166.81
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /home/gburi-arabmed/htdocs/arabmed.gburi.dev/public/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/
          README.md
          .gitignore
        
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Site should be available at: https://arabmed.gburi.dev"
