name: Deploy Arabmed Laravel App via SSH Key

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout latest code
      - uses: actions/checkout@v4

      # 2️⃣ Execute remote deploy script via SSH key
      - name: Execute remote deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: sh /home/${{ secrets.USERNAME }}/git/deploy.sh
