name: Deploy Laravel App to CloudPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 65.109.166.81
        username: gburi
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 120s
        script: |
          echo "=== Starting Laravel Deployment ==="
          cd /home/gburi-arabmed/htdocs/arabmed.gburi.dev/
          
          # Update Laravel application
          if [ -d "laravel-app/.git" ]; then
            echo "=== Pulling latest changes ==="
            cd laravel-app
            git fetch origin main
            git reset --hard origin/main
            cd ..
          else
            echo "=== First time clone ==="
            sudo rm -rf laravel-app
            git clone git@github.com:HudhaifaGburi2/arabmed.git laravel-app
          fi
          
          echo "=== Installing/Updating Dependencies ==="
          cd laravel-app
          composer install --no-dev --optimize-autoloader --no-interaction
          
          echo "=== Updating Laravel Configuration ==="
          # Copy .env if it doesn't exist
          if [ ! -f ".env" ]; then
            cp .env.example .env
            # Set production environment variables
            sed -i 's/APP_ENV=local/APP_ENV=production/' .env
            sed -i 's/APP_DEBUG=true/APP_DEBUG=false/' .env
            sed -i 's|APP_URL=http://localhost|APP_URL=https://arabmed.gburi.dev|' .env
            sed -i 's/DB_DATABASE=laravel/DB_DATABASE=arabmed_db/' .env
            sed -i 's/DB_USERNAME=root/DB_USERNAME=arabmed_user/' .env
            sed -i "s/DB_PASSWORD=/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env
            php artisan key:generate --force
          fi
          
          # Clear and cache config
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          
          # Optimize for production
          php artisan config:cache
          php artisan view:cache
          php artisan route:cache
          
          echo "=== Updating Web Root ==="
          cd ..
          # Copy Laravel public files to web root
          cp -r laravel-app/public/* public/
          cp laravel-app/public/.htaccess public/ 2>/dev/null || true
          
          # Make sure index.php points to correct Laravel path
          sed -i "s|__DIR__.'/../vendor/autoload.php'|__DIR__.'/../laravel-app/vendor/autoload.php'|g" public/index.php
          sed -i "s|__DIR__.'/../bootstrap/app.php'|__DIR__.'/../laravel-app/bootstrap/app.php'|g" public/index.php
          
          echo "=== Setting Permissions ==="
          chmod -R 755 /home/gburi-arabmed/htdocs/arabmed.gburi.dev/
          chmod -R 775 /home/gburi-arabmed/htdocs/arabmed.gburi.dev/laravel-app/storage
          chmod -R 775 /home/gburi-arabmed/htdocs/arabmed.gburi.dev/laravel-app/bootstrap/cache
          
          echo "=== Laravel Deployment Completed! ==="
          cd laravel-app
          git log --oneline -1
          php artisan --version
    
    - name: Verify deployment
      run: |
        echo "Waiting 15 seconds for deployment to complete..."
        sleep 15
        
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://arabmed.gburi.dev/ || echo "CURL_FAILED")
        
        if [ "$HTTP_STATUS" = "200" ]; then
          echo "✅ Laravel site is responding correctly (HTTP $HTTP_STATUS)"
          echo "🚀 Deployment successful!"
          echo "🌐 Visit: https://arabmed.gburi.dev"
        else
          echo "⚠️ Site returned HTTP $HTTP_STATUS or failed to connect"
          echo "Please check manually: https://arabmed.gburi.dev"
        fi
